/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Externos.Drawer;
import Externos.DrawerItem;
import Externos.EventDrawer;
import Externos.Header;
import java.awt.Color;
import javax.swing.ImageIcon;
import Externos.*;
import Modelagem.Usuario;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 0062928
 */
public class TelaLogin extends javax.swing.JFrame {

    private DrawerController drawer;

    public TelaLogin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new Externos.PasswordField();
        txtName = new Externos.TextField();
        btnNext = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setLabelText("Password");
        txtPassword.setLineColor(new java.awt.Color(51, 51, 51));
        txtPassword.setSelectionColor(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 280, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.setLabelText("User Name");
        txtName.setLineColor(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 177, 280, 60));

        btnNext.setContentAreaFilled(false);
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 280, 30));

        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 403, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/TelaLogin.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<Usuario> usu = new ArrayList();
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        TelaRegistro t = new TelaRegistro();
        t.setLocationRelativeTo(null);
        t.setVisible(true);
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       /* int cont = 0;
        for (int i = 0; i < usu.size(); i++) {
            if (usu.get(i).getNome() == txtName.getName() && usu.get(i).getSenha() == txtName.getText()) {
                TelaMenu t = new TelaMenu();
                t.setVisible(true);
                t.setLocationRelativeTo(null);
                cont++;
            }
        }
        if (cont == 0) {
            JOptionPane.showMessageDialog(null, "Isso ai ta errado princesa");
        }*/
       this.dispose(); 
        TelaMenu t = new TelaMenu();
        t.setVisible(true);
        t.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public ArrayList<Usuario> getU() {
        return usu;
    }

    public void setU(Usuario e) {
        usu.add(e);
    }

    public static void main(String args[]) {
        FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel2;
    private Externos.TextField txtName;
    private Externos.PasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
